Name = "Soup.CSharp.Compiler"
Language = "C#|0.1"
Version = "0.4.1"
Source = [
	"BuildArguments.cs",
	"BuildEngine.cs",
	"BuildResult.cs",
	"CompileArguments.cs",
	"ICompiler.cs",
	"MockCompiler.cs",
]

[Dependencies]
Runtime = [
	{ Reference = "Opal@1.0.3" },
	{ Reference = "Soup.Build@0.1.4", ExcludeRuntime = true },
	{ Reference = "Soup.Build.Extensions@0.2.0" },
	{ Reference = "Soup.Build.Extensions.Utilities@0.2.1" },
]